# Generated by Django 4.2.6 on 2023-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='url_text',
            field=models.CharField(default='Click', max_length=30),
        ),
    ]
