# Generated by Django 4.2.6 on 2023-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_carousel_url_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='features')),
            ],
        ),
    ]
