# Generated by Django 4.2.6 on 2023-11-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='url_text',
        ),
    ]
