# Generated by Django 4.2.6 on 2023-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_carousel_url_remove_carousel_url_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=256),
        ),
    ]
