# Generated by Django 4.2.6 on 2023-11-25 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_carousel_url_remove_carousel_url_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='add_to_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='new-page', editable=False, max_length=256, unique_for_date='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
