# Generated by Django 4.2.6 on 2023-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, unique=True),
        ),
    ]
