# Generated by Django 4.2.6 on 2023-12-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_message_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
    ]
