# Generated by Django 4.2.6 on 2023-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/post.jpg', upload_to='posts'),
        ),
    ]
